# Generated by Django 3.0.7 on 2020-06-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, null=True)),
                ('password', models.CharField(max_length=30, null=True)),
                ('idcard', models.CharField(max_length=30, null=True)),
                ('borrowed', models.IntegerField(max_length=5, null=True)),
                ('staff', models.IntegerField(max_length=2, null=True)),
                ('deposit', models.IntegerField(max_length=5, null=True)),
            ],
        ),
    ]
